# Generated by Django 4.1.3 on 2023-02-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.FloatField(max_length=20, verbose_name='Количество на складе')),
                ('price', models.FloatField(max_length=30, verbose_name='Цена')),
                ('uuid_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy_shop.category', verbose_name='Категории товара')),
                ('uuid_sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy_shop.sex', verbose_name='Пол')),
            ],
        ),
    ]
